# Generated by Django 4.1.1 on 2022-09-09 15:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_org', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('total', models.FloatField()),
                ('date', models.DateField()),
                ('service', models.TextField(validators=[django.core.validators.MinLengthValidator(1)])),
            ],
        ),
    ]
